title: Pareto Verteilung 1
question: |
  Welches Parameterpaar definiert die Pareto-Verteilung?

  A) Mittelwert und Varianz.
  
  B) Exponent ğ›¼ und Skalenparameter $x_m$.
  
  C) Erwartungswert und Standardabweichung.
  
  D) Median und Modus.
solution: B
