title: Pareto Verteilung 2
question: |
  Was ist der Parameter ğ›¼ in einer Pareto-Verteilung?

  A) Der Parameter ğ›¼ beschreibt die Breite der Verteilung und bestimmt, wie viele AusreiÃŸer existieren.
  
  B) Der Parameter ğ›¼ ist der Mittelwert der Verteilung und beeinflusst, wie schmal oder breit die Verteilung ist.
  
  C) Der Parameter ğ›¼ ist der Formparameter der Verteilung, der steuert, wie schnell die Wahrscheinlichkeit abnimmt.
  
  D) Der Parameter ğ›¼ ist irrelevant und beeinflusst nicht die Form der Verteilung.
solution: C
