title: Pareto Verteilung 4
question: |
  Gegeben sei eine Pareto-Verteilung mit dem Parameter ğ›¼ = 2 und dem minimalen Wert $x_m$ = 1.
  Berechnen Sie die Wahrscheinlichkeit, dass ein Wert grÃ¶ÃŸer als 3 ist, also $ğ‘ƒ(ğ‘‹ > 3)$.

  Formel: $S(x) = P(X \geq x) = (\frac{x_{m}}{x})^Î±$
solution: Die Wahrscheinlichkeit, dass $ğ‘‹ > 3$, betrÃ¤gt $\frac{1}{9}$
